### PR TITLE
ng add as dev dependency

### PR DESCRIPTION
**Pull request by muuvmuuv**
Install cypress-schematic as dev dependency

closes: #43

### CODE REVIEW

**Comment by muuvmuuv** [comment]
Why on earth is it now 37 again?! 

```
Message:
    Expected 37 to equal 38.
```

**Comment by muuvmuuv** [comment]
Seems like some weird package-lock issue. Just deleting and `npm i` again produced multiple `rxjs` errors. Thats because I updated the dependencies and updated the numnber. I love npm.

**Comment by anthonymjones** [comment]
Nice!

**Comment by anthonymjones** [comment]
@muuvmuuv - Everything looked good, until I went to publish. For some reason when `@briebug/cypress-schematic` is a `devDependency` in the sandbox, the `npm run clean` script does not work. When I remove it, everything works again. I'm not sure exactly why yet.

**Comment by anthonymjones** [comment]
@schuchard - Do you know why this may be happening? I notice on the jest-schematic `@briebug/jest-schematic` is not a `devDependency` in sandbox.

**Comment by muuvmuuv** [comment]
Then maybe we can remove it at all? We could add `npm link` before `launch` so the current version is getting added without installing it before.

**Comment by anthonymjones** [comment]
Adding the link in the launch script before cd'ing into sandbox appears to work.

**Pull request merged**
