### PR TITLE
add cypress 5 support

### PR DESCRIPTION
**Pull request by muuvmuuv**
This PR adds support for Cypress version 5.

I am not quite sure how add tests to the builder but run the tests without errors.

I have also changed the prettier config because it seemed the previous prettier config was malformed and therefore didn't do anything. That is way it is a mess ^^ haven't seen that it will be auto formated on commit.

closes: #42 
closes: #47

### CODE REVIEW

**Comment by muuvmuuv** [comment]
I also made Node 12 minimum because 8 is outdated and 10 is in maintenance: https://github.com/nodejs/Release 
But I can revert that if you want.

**Comment by anthonymjones** [comment]
Hi Marvin, thanks for the contribution! I updated the workflow in Master to remove the Node 8.x build. Will you please rebase and push so that we can see the workflow pass?

**Comment by muuvmuuv** [comment]
Hey @anthonymjones, I have put the min node version back to 10 and also increased the scaffold size in `index_spec.ts`. I think it failed because newer NG cli creates a solution style tsconfig which adds `tsconfig.app.json`.

**Comment by anthonymjones** [comment]
Great work! Thank you for knocking out these two issues. If you're interested and have the time, I'd love your help addressing some of the other open issues 👍

**Pull request merged**
