### PR TITLE
Migrate all projects from workspace (angular.json)

### PR DESCRIPTION
**Pull request by konstantindenerz**
Issue #30 

## What I did
I have changed the behaviour from migration only default project (from angular.json) or given from options to *process all projects* (from angular.json).
I added a second app to `sandbox-workspace` to test this.

## How to test?
I can use this command `npm run clean:launch:ws` to run tests.

The current PR depends on this PR #70. Create an e2e folder before testing or comment out the e2e folder deletion to run the test without #70.

> Please add  the new [hacktoberfest-accepted](https://hacktoberfest.digitalocean.com/details#details) label to this PR if you accept the PR.

### CODE REVIEW

**Comment by anthonymjones** [comment]
Do you get a successful output when you run `npm run test:ws`? I'm still seeing the `Path "/e2e" does not exist.` error. This error is happening because the `removeFiles` method is only looking at the root of the workspace for the `/e2e` directory. With the standard sandbox, this works, but with the workspace, the `/e2e` directories are nested under each project. 

Seems like the best strategy would be to traverse the projects (determined in the angular.json) and remove the `/e2e` for each. What do you think?

**Comment by konstantindenerz** [comment]
@anthonymjones Thats right, the error will be fixed after the merge of PR #70. Good idea to remove e2e folder of each project. I will change the PR.

**Comment by konstantindenerz** [comment]
@anthonymjones, now I traverse the projects and delete e2e directories (and the old *-e2e applications).

**Comment by anthonymjones** [comment]
@konstantindenerz, nice work! This one is ready to rebase.

**Comment by konstantindenerz** [comment]
@anthonymjones I'm done :) Could you add the hacktoberfest-accepted label to accelerate the tracking?

**Review by anthonymjones — APPROVED** [review]

**Pull request merged**
