### PR TITLE
chore: add sandbox with Angular CLI v12

### PR DESCRIPTION
**Pull request by cexbrayat**
CLI v12 rc.0 is out, and Protractor is now removed from a new project.

This is PR adds a new sandbox generated with v12 rc.0, and adds the tests to the CI config.

It is currently failing even with "--no-remove-protractor" because the "e2e" target no longer exists, so using the schematics adds "cypress-un" and "cypress-open" to angular.json but not the "e2e" target.
A following PR is fixing the issue.

### CODE REVIEW

**Comment by anthonymjones** [comment]
Looks like we just need to rebase now that #102 is merged.

**Comment by cexbrayat** [comment]
#102 was on top of this one, so we can just close 👍

Do you think you can cut a release (even a beta) so we can test all these changes and fixes?

**Comment by anthonymjones** [comment]
Yep, working on a release now. I have a branch converting the sandboxes from karma to jest that I'd like to get in first

**Comment by cexbrayat** [comment]
Awesome, thanks @anthonymjones

**Pull request closed without merging**
